"""
Django settings for event_management project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Load environment variables from .env
dotenv_path = os.path.join(BASE_DIR, ".env")
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wqk6_y73o3ut26x+l7el&qiyihfi@@duw3*n*3w=89xf58#ii7"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = ["*",]
CSRF_TRUSTED_ORIGINS = [
    "http://198.199.79.173:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8000",

    "https://qrscanner.innovedu.com/",

    "https://qrscanner.innovedu.com",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "crispy_forms",
    "crispy_tailwind",
    "ckeditor",
    "widget_tweaks",
    "heroicons",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# Content-Security-Policy (OWASP ZAP remediation). All vendor JS/CSS is now
# self-hosted (see core/static/vendor/), except Stripe.js which must be
# loaded directly from Stripe's CDN for PCI compliance/fraud detection.
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "script-src": ["'self'", "'unsafe-inline'", "https://js.stripe.com"],
        "style-src": ["'self'", "'unsafe-inline'"],
        "frame-src": ["'self'", "https://js.stripe.com", "https://hooks.stripe.com"],
        "connect-src": ["'self'", "https://api.stripe.com"],
        "img-src": ["'self'", "data:"],
    }
}

# Celery Beat Scheduler
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_RESULT_EXPIRES = 60 * 60 * 24  # keep results 24 h
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = "Asia/Nicosia"

ROOT_URLCONF = "event_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": [
                "heroicons.templatetags.heroicons",
            ],
        },
    },
]

WSGI_APPLICATION = "event_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ✅ Determine if we're in development or production
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"


# ✅ Only true on the real deployment, where nginx terminates TLS in front of
# Django (see nginx/default.conf). DEBUG=False just means "use Postgres" in
# this project's docker-compose, including local runs with no real TLS on
# port 8000 — so SSL-redirect/HSTS must NOT be tied to DEBUG, or every local
# request gets 301-redirected to https:// on a port that only speaks HTTP.
BEHIND_TLS_PROXY = os.getenv("DJANGO_BEHIND_TLS_PROXY", "False") == "True"

# Cookie & transport security hardening (OWASP ZAP remediation)
SESSION_COOKIE_SECURE = BEHIND_TLS_PROXY
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = BEHIND_TLS_PROXY
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_SSL_REDIRECT = BEHIND_TLS_PROXY
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

if BEHIND_TLS_PROXY:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ✅ Database Configuration
# if DEBUG == "True":
# 💻 DEVELOPMENT: Use SQLite
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# print("🚀 Running in DEVELOPMENT mode with SQLite")
# else:
# # 🌍 PRODUCTION: Use MySQL
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": os.getenv("MYSQL_DATABASE"),
#         "USER": os.getenv("MYSQL_USER"),
#         "PASSWORD": os.getenv("MYSQL_PASSWORD"),
#         "HOST": f"{os.getenv('MYSQL_HOST')}",
#         "PORT": os.getenv("MYSQL_PORT"),
#         "OPTIONS": {
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }
# print("🌍 Running in PRODUCTION mode with MySQL")
# 🌍 PRODUCTION: Use PostgreSQL (Docker)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB"),
#         "USER": os.getenv("POSTGRES_USER"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
#         "HOST": os.getenv("POSTGRES_HOST"),  # should be 'db'
#         "PORT": os.getenv("POSTGRES_PORT"),  # usually 5432
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("db_name"),
        "USER": os.getenv("db_username"),
        "PASSWORD": os.getenv("db_password"),
        "HOST": os.getenv("db_host"),  # should be 'db'
        "PORT": os.getenv("db_port"),  # usually 5432
    }
}
print("🌍 Running in PRODUCTION mode with PostgreSQL")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Nicosia"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "core", "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Tell crispy forms to use Tailwind
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

LOGIN_URL = "/login/"

# Site URL for generating absolute URLs in emails
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# Stripe API Version
STRIPE_API_VERSION = "2024-06-20"



PDF_REPLACEMENT_FONT = os.getenv(
    "PDF_REPLACEMENT_FONT",
    os.path.join(BASE_DIR, "core", "static", "fonts", "DejaVuSans.ttf"),
)

