# Generated by Django 5.1.6 on 2025-02-14 20:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_end_time_event_start_time_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.event_image_path),
        ),
    ]
