# Generated by Django 5.1.6 on 2025-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_status_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
