# Generated by Django 5.1.6 on 2025-02-19 12:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='pdf_ticket',
            field=models.FileField(blank=True, null=True, upload_to=core.models.pdf_ticket_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.qr_code_path),
        ),
    ]
