# Generated by Django 5.1.6 on 2025-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_participant_pdf_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='priority',
            field=models.IntegerField(default=99, help_text='Lower numbers have higher priority. Completed events should have a higher number.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='signature_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
