# Generated by Django 5.1.6 on 2025-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_registration_enabled',
            field=models.BooleanField(default=False, help_text='Enable this if you want to allow public registration via link.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='signatures',
            field=models.BooleanField(default=False, help_text='Enable this if you want to collect signatures from participants at the event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.BooleanField(default=False, help_text='Enable this if you want to have ticketing system for the event.'),
        ),
    ]
