# Generated by Django 5.1.6 on 2025-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_eventcustomfield_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='submitted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
