# Generated by Django 5.1.6 on 2025-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_participant_submitted_data_delete_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('range', 'Range'), ('checkbox', 'Checkbox'), ('multiselect', 'Multi-select')], max_length=20),
        ),
    ]
