# Generated by Django 5.1.6 on 2025-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_eventcustomfield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcustomfield',
            name='is_email_identifier',
        ),
        migrations.AlterField(
            model_name='eventcustomfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('range', 'Range'), ('checkbox', 'Checkbox'), ('multiselect', 'Multi-select'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventcustomfield',
            name='options',
            field=models.TextField(blank=True, help_text="Comma-separated options (for 'select' and 'multiselect' types) or min,max values (for 'range' type)"),
        ),
        migrations.AlterField(
            model_name='eventcustomfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
