# Generated by Django 5.1.6 on 2025-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_help_text_to_custom_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcustomfield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='eventcustomfield',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order of this field (1 = first, 2 = second, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcustomfield',
            unique_together={('event', 'order')},
        ),
    ]
