# Generated by Django 5.1.6 on 2025-06-20 11:56

from django.db import migrations


def assign_unique_order_numbers(apps, schema_editor):
    """Assign unique order numbers to existing custom fields."""
    EventCustomField = apps.get_model("core", "EventCustomField")

    # Group custom fields by event
    events_with_fields = {}
    for field in EventCustomField.objects.all():
        if field.event_id not in events_with_fields:
            events_with_fields[field.event_id] = []
        events_with_fields[field.event_id].append(field)

    # Assign unique order numbers for each event
    for event_id, fields in events_with_fields.items():
        for index, field in enumerate(fields, start=1):
            field.order = index
            field.save()


def reverse_assign_order_numbers(apps, schema_editor):
    """Reverse the order assignment (set all to 1)."""
    EventCustomField = apps.get_model("core", "EventCustomField")
    EventCustomField.objects.all().update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_eventcustomfield_options_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_unique_order_numbers, reverse_assign_order_numbers),
    ]
