# Generated by Django 5.1.6 on 2025-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250620_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcustomfield',
            unique_together=set(),
        ),
    ]
