# Generated by Django 5.1.6 on 2025-06-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_eventcustomfield_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcustomfield',
            unique_together={('event', 'order')},
        ),
    ]
