# Generated by Django 5.1.6 on 2025-06-23 11:34

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_eventcustomfield_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('select', 'Select'), ('range', 'Range'), ('checkbox', 'True or False'), ('multiselect', 'Multi-select'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('file', 'File Upload')], max_length=20),
        ),
        migrations.CreateModel(
            name='ParticipantCustomFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=core.models.custom_field_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_files', to='core.participant')),
            ],
        ),
    ]
