# Generated by Django 5.1.6 on 2025-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_eventcustomfield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_approval_enabled',
            field=models.BooleanField(default=True, help_text='Enable this if you want registrations to be automatically approved. If disabled, registrations will require manual approval.'),
        ),
    ]
