# Generated by Django 5.1.6 on 2025-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_event_auto_approval_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text="Status of the participant's registration approval", max_length=20),
        ),
    ]
