# Generated by Django 5.1.6 on 2025-06-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_participant_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('registration', 'On Registration')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use placeholders like {{ name }}, {{ event_name }}, {{ event_date }}')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.event')),
            ],
            options={
                'unique_together': {('event', 'reason')},
            },
        ),
    ]
