# Generated by Django 5.1.6 on 2025-06-26 11:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_eventemail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemail',
            name='body',
            field=ckeditor.fields.RichTextField(help_text='Use placeholders like {{ name }}, {{ event_name }}, {{ event_date }}, {{ rsvp_accept_url }}, {{ rsvp_decline_url }}, {{ rsvp_maybe_url }}. HTML formatting is supported.'),
        ),
        migrations.AlterField(
            model_name='eventemail',
            name='reason',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('registration', 'On Registration'), ('rsvp', 'RSVP Request')], max_length=20),
        ),
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('attend', 'Attend'), ('cant_make_it', "Can't make it"), ('maybe', 'Maybe')], max_length=12)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the participant', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='core.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='core.participant')),
            ],
            options={
                'unique_together': {('participant', 'event')},
            },
        ),
    ]
