# Generated by Django 5.1.6 on 2025-07-01 07:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_eventemail_options_rsvpemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload a certificate template file (PDF, DOC, DOCX, PNG, JPG) for this event.', null=True, upload_to=core.models.event_certificate_path),
        ),
    ]
