# Generated by Django 5.1.6 on 2025-07-01 08:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=core.models.participant_certificate_path),
        ),
    ]
