# Generated by Django 5.1.6 on 2025-07-02 07:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_participant_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload a PDF certificate template file for this event. Use placeholders like {{participant_name}}, {{event_name}}, {{event_date}}, {{company_name}} for personalization.', null=True, upload_to=core.models.event_certificate_path, validators=[core.models.validate_pdf_file]),
        ),
    ]
