# Generated by Django 5.1.6 on 2025-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_certificategenerationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemail',
            name='reason',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('registration', 'On Registration'), ('rsvp', 'RSVP Request'), ('certificates', 'Certificate Generation')], max_length=20),
        ),
    ]
