# Generated by Django 5.1.6 on 2025-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_eventemail_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_registration_limit',
            field=models.BooleanField(default=False, help_text='Enable this if you want to limit the number of registrations for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed to register (only applies if registration limit is enabled).', null=True),
        ),
    ]
