# Generated by Django 5.1.6 on 2025-07-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_event_has_registration_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpemaillog',
            name='action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
