# Generated by Django 5.1.6 on 2025-07-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rsvpemaillog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvpemaillog',
            old_name='error_message',
            new_name='log_message',
        ),
    ]
