# Generated by Django 5.1.6 on 2025-07-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_error_message_to_log_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificategenerationlog',
            old_name='error_messages',
            new_name='log_messages',
        ),
        migrations.RenameField(
            model_name='csvimportlog',
            old_name='error_messages',
            new_name='log_messages',
        ),
    ]
