# Generated by Django 5.1.6 on 2025-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_error_messages_certificategenerationlog_log_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvpemaillog',
            name='log_message',
        ),
        migrations.AddField(
            model_name='rsvpemaillog',
            name='log_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
