# Generated by Django 5.1.6 on 2025-07-14 12:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_log_message_to_log_messages_rsvpemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certificate',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models.participant_certificate_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pdf_ticket',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models.pdf_ticket_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=core.models.qr_code_path),
        ),
    ]
