# Generated by Django 5.1.6 on 2025-07-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_order_payment_tickettype_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_tickets',
            field=models.BooleanField(default=False, help_text='Enable this if tickets require payment. Only applies when ticketing is enabled.'),
        ),
    ]
