# Generated by Django 5.1.6 on 2025-07-16 12:27

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_event_paid_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=core.models.qr_code_path)),
                ('scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_tickets', to='core.order')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participant')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tickettype')),
            ],
        ),
    ]
