# Generated by Django 5.1.6 on 2025-07-16 13:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_paidticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidticket',
            name='pdf_ticket',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models.paid_ticket_pdf_path),
        ),
    ]
