# Generated by Django 5.1.6 on 2025-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_paidticket_pdf_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps link for the event location. Copy and paste the Google Maps URL here.', max_length=500, null=True),
        ),
    ]
