# Generated by Django 5.1.6 on 2025-09-17 07:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_event_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='consent_disclaimer',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional GDPR / consent disclaimer shown on the registration form.', null=True),
        ),
    ]
