# Generated by Django 5.1.6 on 2025-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_event_consent_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_cutoff_hours',
            field=models.PositiveIntegerField(default=48, help_text='How many hours before the event start RSVPs are locked. For example: 2 = 2 hours before, 24 = 1 day before.'),
        ),
    ]
