# Generated by Django 5.1.6 on 2026-06-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_event_status'),
        ('core', '0049_eventsystemfieldconfig_active'),
    ]

    operations = [
    ]
